### PR TITLE
Add PR template prototype

### PR DESCRIPTION
**Pull request by JesusValera**
# Description

The idea of this PR is to create a _pull request template_ as a prototype in order to set a kind of "agreement" for new PRs.

It is very handy and it is automatically integrated into GitHub.

Take a look and tell me what do you think.

### CODE REVIEW

**Comment by jenshaase** [comment]
I though about this myself too. However, I came to the conclusion that this is to much of a process for this early stage. I don't want people to stuck in to many processes right now. But I'm open for a discussion on this.

As alternative we could think of a small contributions guide where we could give some best practices on submitting a pull request.

**Comment by JesusValera** [comment]
> I though about this myself too. However, I came to the conclusion that this is to much of a process for this early stage. I don't want people to stuck in to many processes right now. But I'm open for a discussion on this.
> 
> As alternative we could think of a small contributions guide where we could give some best practices on submitting a pull request.

Well, the point of this PR is to unify and simplify the PRs.
You can take a look at those PRs (I took a random one of each contributor) :

https://github.com/jenshaase/phel-lang/pull/36 -> @JesusValera
https://github.com/jenshaase/phel-lang/pull/23 -> @paullaffitte
https://github.com/jenshaase/phel-lang/pull/18 -> @Chemaclass
https://github.com/jenshaase/phel-lang/pull/11 -> @dominikb 

By one side, I think it makes simple the process,
by the other, I agree with you maybe it makes more complicated the process of creating new PRs.

About your suggestion, what do you mean with "small contribution guide"?

You can close this PR, and create an issue with that. :smile:

**Comment by Chemaclass** [comment]
I agree with @jenshaase. But I like the proposal idea from @JesusValera too. 
What about making it simpler? I would propose a minimalistic template like:

```
# Description

Replace this text by a short description of your feature/bugfix. 
This will help people understand your PR and can be used as a start for the docu.

# Changes

- Modified X class/method to do Y because Z
```

What do you think?

**Comment by jenshaase** [comment]
Hi,

I would go for an even simple and more open template. This will also work for documentation changes.
```
# Description

Replace this text by a short description of your feature/bugfix. 

# Changes

- List individual changes in more detail
```

What do you think?

**Comment by Chemaclass** [comment]
> Hi,  I would go for an even simple and more open template. This will also work for documentation changes.
> ```
> # Description
> 
> Replace this text by a short description of your feature/bugfix. 
> 
> # Changes
> 
> - List individual changes in more detail
> ```
> 
> What do you think?

Yes! I like this even more.

**Comment by JesusValera** [comment]
I like even more now! :smile: 

Done.

**Comment by jenshaase** [comment]
Thanks. Merged it!

**Pull request merged**
