### PR TITLE
Update Readme file with the logo

### PR DESCRIPTION
**Pull request by JesusValera**
# 📚 Description

I think the `readme` file improves a lot with a picture.

That's why I have done something similar to what [Haxe](https://github.com/HaxeFoundation/haxe) did, but I am not 100% happy with the final result. What do you think about the icon disposition? Maybe a smaller picture could fit better, doesn't it? 😃 

Take a look at [Janet](https://github.com/janet-lang/janet) too (just for mentioning other functional languages).

Also, do we have any other badges which is not included? 🤔 

# 💡 Extra

### Actually, I think we can collapse the PHP 8 doc like:

. . .

### Run on PHP 8 with JIT

<details><summary>Show / Hide</summary>
<p>

The JIT compiler in PHP 8 provides more speed for the Phel compiler. To compare the runtime on PHP 7.4 vs PHP 8 the following commands can be used.

First, pull the docker image

```
docker pull keinos/php8-jit:latest
```

Run the PHPUnit tests
```
sudo docker run --rm \
    -v $(pwd):/app \
    -w /app \
    keinos/php8-jit \
    ./vendor/bin/phpunit
```

Run the Phel test suite
```
sudo docker run --rm \
    -v $(pwd):/app \
    -w /app \
    keinos/php8-jit \
    php tests/phel/test-runner.php
```

</p>
</details>

### CODE REVIEW

**Comment by mabasic** [comment]
Maybe a transparent image with purple lines for the elephant.

**Comment by jenshaase** [comment]
You could put the `width` and `height` attributes to the image to make it small (maybe 200px). 
As alternative you can find the original image in the root folder (logo.svg). I designed it with Inkscape.

**Comment by JesusValera** [comment]
Done.

**Comment by mabasic** [comment]
It think that it would probably look much cooler with thicker purple lines

**Comment by JesusValera** [comment]
> It think that it would probably look much cooler with thicker purple lines

Probably, could you do it @jenshaase? :)

**Comment by jenshaase** [comment]
I added an SVG with purple lines: See `/doc/static/logo.svg`. @JesusValera Can you add it to the Readme?

**Review by Chemaclass — APPROVED** [review]
Nice :)

**Comment by jenshaase** [comment]
Looks very good now. Thanks. It is merged!

**Pull request merged**
