### PR TITLE
Implementing rand-nth

### PR DESCRIPTION
**Pull request by Chemaclass**
## 🔖 Changes

- Added `rand-nth`: it returns a random item from xs.

### Tests

```lisp
(rand-nth @["one" "or" "other"])
``` 
It will get one of these: "one", "or", "other"

### CODE REVIEW

**Comment by jenshaase** [comment]
Hi,

there is a script to build the API documentation: `doc/build-api-page.php`. Have you used that?

**Comment by Chemaclass** [comment]
No, I did it manually. 
Should I run `php doc/build-api-page.php` and that's it? 
Or should I redirect the output of that script to a certain file or somewhere?
Or how should I generate the API documentation? Is that documented somewhere?

About the docu I just found that command that you wrote me + in the README.md at the bottom it says
```
# Build the documentation
## The documentation is built with Zola.

cd doc
zola serve # build & serve
zola build # build & publish
```
🤔

**Comment by jenshaase** [comment]
It should be `php doc/build-api-page.php > doc/content/documentation/api.md`

**Comment by Chemaclass** [comment]
Ach, way too many changes... 
I would keep this PR simple and merge only the new function (removing the last commit). And in another commit directly to master (or PR) update the full docu from API. Fine for you, @jenshaase?

**Comment by jenshaase** [comment]
Yes that is ok for me. You can commit it directly to master.

**Review by jenshaase — APPROVED** [review]

**Comment by jenshaase** [comment]
It is merged now. Thanks!

**Pull request merged**
