### PR TITLE
Refactor Destructure class

### PR DESCRIPTION
**Pull request by Chemaclass**
Issue: https://github.com/jenshaase/phel-lang/issues/142

## 📚 Description

I moved away from the `Destructure` class that remains in the root project and it doesn't belong there.

## 🔖 Changes

- Splitting using extract class refactoring the `Destructure` class.
- Moved the `Destructure` class to its own submodule inside the `...\TupleSymbol\Binding\Deconstructor` folder.
- Renamed `Destructure` to `TupleDeconstructor` class.
- Added unit tests for the `TupleDeconstructor` and other `BindingDeconstructors`.

### CODE REVIEW

**Review by JesusValera — APPROVED** [review]
What a fantasy ✨

**Review by JesusValera — APPROVED** [review]

**Review by jenshaase — APPROVED** [review]
Thanks. Code looks good!

The tests are ok for now. But I think they don't look very natural. I think I would do them slightly different to have more real world examples. However, it is too hard for me to explain it in the comments. I probably will change them on my own.

**Comment by Chemaclass** [comment]
Yes, @jenshaase , that would be awesome. I got really hard time trying to figure out myself how to write them 😂

**Comment by JesusValera** [comment]
Yes, the test are very complicated 🤓

**Pull request merged**
