### PR TITLE
Implement str-contains? in phel

### PR DESCRIPTION
**Pull request by Chemaclass**
## 📚  Description

I was thinking about to implement something like the new [`str_contains`](https://www.php.net/manual/en/function.str-contains) (able in PHP 8). So I did.

## 🔖 Changes

- Added the `str-contains?` function in phel with some unit tests
- Updated the API docu using `php doc/build-api-page.php > doc/content/documentation/api.md`

### CODE REVIEW

**Review by JesusValera — APPROVED** [review]

**Comment by jenshaase** [comment]
What I don't like is the name `includes?` can also mean that you want to check if a value is in an array. To solve it there are two options in my opinion.

1. Move all string method to a separate namespace. It is no much clearer that `includes?` belongs to strings. However, you then have to to load the namespace in every file want to work with strings. Clojure did this. However, in the Web-Dev-World you work a lot with string. Therefore, I would like to have them in `phel\core`.
2. Have a name prefix on string methods like `string-includes?` or `str-includes?`.

What do you think?

**Comment by Chemaclass** [comment]
mmm, you got a valid point. In that case, to keep the compatibility with the upcoming (in php8) str_contains, I will rename it to `str-contains` and everyone is happy. Thumbs up for your confirmation, @jenshaase 

PS: I don't think we need the `?` in this function name, do we? Like `str-contains?`
Or do we have that convention to end with `?` all bool-returning functions in phel? 🤔

**Comment by jenshaase** [comment]
I would like to have the conventions that all functions that return a boolean, have `?` and the end. 

I think I mostly did that but I didn't wrote it down yet. It is on my list. Therefore, I would like to have a `adrs/phel` directory.

**Comment by Chemaclass** [comment]
Perfect. Then you can merge this one :)

**Review by jenshaase — APPROVED** [review]

**Comment by jenshaase** [comment]
Ok merged! Thank you!

**Pull request merged**
